import {
  IconAlertTriangle,
  IconArrowRight,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconCreditCard,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconPhoto,
  IconDeviceLaptop,
  IconLayoutDashboard,
  IconLoader2,
  IconLogin,
  IconProps,
  IconShoppingBag,
  IconMoon,
  IconDotsVertical,
  IconPizza,
  IconPlus,
  IconSettings,
  IconSun,
  IconTrash,
  IconBrandTwitter,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconX,
  IconLayoutKanban,
  IconBrandGithub,
  IconBuildingSkyscraper,
  IconBed,
  IconHome,
  IconBath,
  IconAlertCircle,
  IconChartBar,
  IconTrendingUp,
  IconReceipt,
  IconCash,
  IconShoppingCart,
  IconBox,
  IconTruckDelivery,
  IconClipboardList,
  IconBuildingStore,
  IconUsers,
  IconShieldLock,
  IconKey,
  IconListDetails,
  IconTags,
  IconCategory,
  IconAdjustmentsAlt,
  IconArrowsRightLeft,
  IconBuildingEstate,
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  product: IconShoppingBag,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  check: IconCheck,
  building: IconBuildingSkyscraper,
  bed: IconBed,
  home: IconHome,
  bath: IconBath,
  alertCircle: IconAlertCircle,
  
  // New icons for sidebar
  chart: IconChartBar,
  trendingUp: IconTrendingUp,
  receipt: IconReceipt,
  cash: IconCash,
  shoppingCart: IconShoppingCart,
  box: IconBox,
  truck: IconTruckDelivery,
  clipboard: IconClipboardList,
  store: IconBuildingStore,
  users: IconUsers,
  shield: IconShieldLock,
  key: IconKey,
  list: IconListDetails,
  tags: IconTags,
  category: IconCategory,
  adjustments: IconAdjustmentsAlt,
  transfer: IconArrowsRightLeft,
  estate: IconBuildingEstate,
};
